### ISSUE TITLE
Question: How to receive value from previous nodes?

### ISSUE THREAD

**Issue by deshdeep-airwallex** [naskio/n8n-nodes-python#2]
Hey @naskio Thanks for putting this package together. Do you have examples of how we can receive the items from previous nodes?  Cheers

**Comment by naskio** [comment]
Hello
You can find in the README.md *Usage section" which contains an example
```
for item in items:
    print(item) # item from previous node
```
Good luck
note: for now, it is only possible to access data from the previous node however you can add an intermediary node to make accessing other nodes data possible.

**Comment by deshdeep-airwallex** [comment]
Hey @naskio Thanks for your prompt response. I don't see a example which tells how to receive items from a specific node. Have I missed something? Cheers
