### ISSUE TITLE
ERROR: exitCode: 0 spawn python3 ENOENT

### ISSUE THREAD

**Issue by pablorq** [naskio/n8n-nodes-python#9]
Hi!

I'm testing this node but the 'ERROR: exitCode: 0 spawn python3 ENOENT [Line xxx]' cames on every code tested.

For example:
```
new_items = []
for item in items:
		item['newField'] = 'newValue'
		new_items.append(item)
return new_items # should return a list
```
```
print(items)
# > list
return items
```

n8n: v0.224.1
n8n-nodes-python: v0.1.4

It seems to be a problem with the path on the node.js code:
https://stackoverflow.com/questions/55033450/spawn-python-enoent-node-js-in-windows
https://stackoverflow.com/questions/58390884/how-to-fix-error-spawn-py-enoent-error-when-running-python-script-from-electr
https://stackoverflow.com/questions/47099422/error-spawn-python-enoent

**Comment by pablorq** [comment]
Same problem with:

n8n: v0.225.2
n8n-nodes-python: v0.1.4

**Comment by pablorq** [comment]
Never mind!

I was using the official n8n docker, without python. Changing to naskio/n8n-python:0.222.0 solves this issue, because now it has python!

Waiting for the new images supporting node v18.

**Comment by naskio** [comment]
Hi guys,
FYI, the latest version of naskio/n8n-python (v0.226.0) uses Node v18.

**Comment by pablorq** [comment]
Yes. I was waiting for the new docker image to be published.

Now it works fine!

:+1:
